SET SCHEMA FN71878@

-- INSERT INTO SEASON

--1 DONE
INSERT INTO SEASON (TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES('NOVA TV', 2013, 12, '2013-03-05', '2013-06-05', 'car', 6)@
--2 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2014, 13, '2014-03-10', '2014-06-09', 'car', 14)@
--3 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2015, 13, '2015-03-03', '2015-05-25', 'car', 22)@
--4 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2016, 13, '2016-03-03', '2016-05-30', 'car', 28)@
--5 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2017, 13, '2017-03-27', '2017-05-29', 'car', 39)@
--6 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2018, 13, '2018-02-26', '2018-05-28', 'car', 45)@
--7 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2019, 13, '2019-02-25', '2019-05-27', 'car', 55)@
--8 DONE
INSERT INTO SEASON(TV_CHANNEL, YEAR_OF_BROADCASTING, EPISODES, START_DATE, FINAL_DATE, AWARD, WINNER_ID)
VALUES ('NOVA TV', 2020, 13, '2020-02-24', '2020-05-18', 'car', 65)@

-- EPISODES IN SEASON 1  ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,23)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,23)@

-- EPISODES SEASON 2   ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,24)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,24)@

-- EPISODES SEASON 3   ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,25)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,25)@

DELETE FROM EPISODE WHERE EPISODE_ID=13 AND SEASON_ID=25@

-- EPISODES SEASON 4   ALL CREATED  
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,26)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,26)@

-- EPISODES SEASON 5    ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,27)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,27)@

-- EPISODES SEASON 6      ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,28)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,28)@

-- EPISODES SEASON 7   ALL CREATED  
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,29)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,29)@

-- EPISODES SEASON 8   ALL CREATED
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (1,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (2,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (3,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (4,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (5,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (6,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (7,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (8,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (9,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (10,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (11,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (12,30)@
INSERT INTO EPISODE(EPISODE_ID, SEASON_ID)
VALUES (13,30)@


-- PARTICIPANTS IN SEASON 1   ALL CREATED
INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Albena Mihova', null, 'F', 45, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Alexei Kozhuharov', null, 'M', 45, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Diana Lybenova', null, 'F', 47, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Maria Ignatova', null, 'F', 40, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Milica Gladnishka', null, 'F', 35, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Raffy Bohosiyan', null, 'M', 27, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Stanimir Gamov', null, 'M', 45, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Stefan Ryadkov', null, 'M', 45, 'actor')@

-- adding in participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (1, 76)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (2, 55)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (3, 51)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (4, 67)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (5, 89)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (6, 91)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (7, 74)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (8, 69)@

-- PARTICIPANTS IN SEASON 2  ALL CREATED
INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Nevena Bozukova', 'Neve', 'F', 47, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Deyan Donkov', null, 'M', 45, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Ivo Tanev', null, 'M', 53, 'showman')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Krastio Vapcarov', 'Kuci', 'M', 56, 'TV host')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Maya Bezhanska', null, 'F', 47, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Antoinette Dobreva', 'Netty', 'F', 44, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Pavel Vladimirov', null, 'M', 40, 'TV host')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Stephanie Koleva', null, 'F', 46, 'actress')@

--adding in table participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (9, 83)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (10, 62)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (11, 76)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (12, 87)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (13, 68)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (14, 101)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (15, 68)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (16, 79)@

-- participants int season 3  ALL CREATED
INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Vasil Boyanov', 'Azis', 'M', 42, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Delyana Marinova', null, 'F', 40, 'TV co-host')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Zhana Bergendorf', null, 'F', 43, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Kristian Talev', 'Krisko', 'F', 31, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Milena Markova', 'Maca', 'F', 43, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Nencho Balabanov', null, 'M', 40, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Nona Yotova', null, 'F', 53, 'actress')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Philip Avramov', 'Phica', 'M', 45, 'actor')@

--adding in table participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (17, 90)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (18, 44)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (19, 72)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (20, 80)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (21, 61)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (22, 96)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (23, 45)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (24, 84)@

-- PARTICIPANTS IN SEASON 4  ALL CREATED
INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Svetozar Hristov', null, 'M', 42, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Gerasim Georgiev', 'Gero', 'M', 45, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Julia Bocheva', null, 'F', 27, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Kalin Vrachanski', null, 'M', 38, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Orlin Pavlov', null, 'M', 41, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Polly Genova', null, 'F', 33, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Petya Ivanova', 'Preslava', 'F', 35, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Preyah Ossasei', null, 'F', 25, 'singer')@

--adding in table participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (25, 63)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (26, 84)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (27, 52)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (28, 88)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (29, 76)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (30, 87)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (31, 70)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (32, 52)@

-- PARTICIPANTS IN SEASON 5  ALL CREATED
INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Bashar Rahal', 'Basho', 'M', 45, 'actor')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Vania Djaferovich', null, 'M', 37, 'footballer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Desislava Doneva', 'Desi Slava', 'F', 37, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Kostadin Georgiev', 'Koceto Kalki', 'M', 57, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Lydmila Dyakovska', 'Lussy', 'F', 44, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Miroslav Kostadinov', 'Miro', 'M', 44, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Mihaela Marinova', null, 'F', 21, 'singer')@

INSERT INTO PEOPLE (PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Sophie Djamandjieva', null, 'F', 29, 'actress')@

-- adding in participant   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (33, 63)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (34, 81)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (35, 88)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (36, 55)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (37, 91)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (38, 83)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (39, 92)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (40, 71)@

-- PARTICIPANTS IN SEASON 6  ALL CREATED
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Borislav Zahariev', 'Bobby the Turbo', 'M', 39, 'actor')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Gery-Nikol Georgieva', null, 'F', 21, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Zlatka Raikova', null, 'F', 34, 'playmate & influencer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Ivan Jurukov', null, 'M', 41, 'actor')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Konstantin Slavchev', null, 'M', 43, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Margarita Hranova', 'Magi', 'F', 68, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Slavin Slavchev', null, 'M', 29, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Sophia Kamenova', 'Sophi Marinova', 'F', 44, 'singer')@

--adding people in participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (41, 71)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (42, 79)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (43, 67)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (44, 82)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (45, 97)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (46, 67)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (47, 85)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (48, 76)@

-- PARTICIPANTS IN SEASON 7   ALL CREATED
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Desislava Dobreva', 'Dessy', 'F', 39, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Dicho Hristov', null, 'M', 46, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Konstantin Trendafilov', 'Pappy Hans', 'M', 27, 'writer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Maria Ilieva', null, 'F', 42, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Milko Kalaidziev', null, 'M', 68, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Petya Bouiklieva', null, 'F', 60, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Stephan Ilchev', null, 'M', 38, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Hristiana Hristova', 'Titta', 'F', 20, 'singer')@

--adding people in participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (49, 77)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (50, 66)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (51, 72)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (52, 83)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (53, 79)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (54, 64)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (55, 97)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (56, 86)@

-- PARTICIPANTS IN SEASON 8   ALL CREATED
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Antoine Petrov', 'Andie', 'M', 28, 'actor')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Galina Kurdova', 'Galia', 'F', 41, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('George Stoimenov', 'JJ', 'M', 30, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Darina Yotova', 'Dara', 'F', 21, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Dimiter Marinov', null, 'M', 55, 'actor')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Luna Yordanova', null, 'F', 49, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Magdalena Dzhanavarova', 'Magi', 'F', 32, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Yonislav Yotov', 'Totto', 'M', 28, 'singer')@

INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Fikret Storaro', 'Fiki', 'M', 25, 'singer')@

--adding participants   ALL CREATED
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (57, 80)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (58, 65)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (59, 88)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (60, 108)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (61, 100)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (62, 42)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (63, 85)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (64, 77)@
INSERT INTO PARTICIPANTS(PARTICIPANT_ID, SUMPOINTS)
VALUES (65, 111)@


---------------INSERT INTO PEOPLE--------------------------------------------------------
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Dimitar Rachkov', 'Rachkov', 'M', 47, 'actor')@ -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Vasil Vaslev', 'Zueka', 'M', 54, 'actor')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Hilda Kazasiyan', null, 'F ', 50, 'singer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Dimitar Kovachev', 'Funky', 'M ', 60, 'musician')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Julian Vergov', null, 'M ', 49, 'actor')@   -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Magardich Halvadzhiyan', 'Magi', 'M ', 53, 'director and producer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Lyben Dilov Son', null, 'M ', 55, 'journalist and writer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Julian Konstantinov', null, 'M ', 54, 'rock & opera singer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Dobrin Vekilov', 'Donny', 'M ', 52, 'singer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Jordanka Hristova', null, 'F', 76, 'singer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Viktor Kalev', 'Vikky', 'M ', 50, 'actor')@   -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Etienne Levi', null, 'M ', 62, 'singer')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('George Nizamov', null, 'M', 50, 'actor')@  -- DONE
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ('Alexandra Eneva', null, 'F', 30, 'dancer')@  -- DONE

-- ADD INTO STAFF   ALL CREATED
INSERT INTO STAFF(STAFF_ID, POSITION)
VALUES (86, 'producer')@
INSERT INTO STAFF(STAFF_ID, POSITION)
VALUES (92, 'singer coach')@
INSERT INTO STAFF(STAFF_ID, POSITION)
VALUES (93, 'actor coach')@
INSERT INTO STAFF(STAFF_ID, POSITION)
VALUES (94, 'dancing coach')@

-- ADD INTO HOSTS   ALL CREATED
INSERT INTO HOSTS(HOST_ID)
VALUES (81)@
INSERT INTO HOSTS(HOST_ID)
VALUES (82)@

-- ADD INTO JUDGES   ALL CREATED
INSERT INTO JUDGES(JUDGE_ID)
VALUES (83)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (84)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (85)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (86)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (87)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (88)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (89)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (90)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (91)@
INSERT INTO JUDGES(JUDGE_ID)
VALUES (5)@






