SET SCHEMA FN71878@

-- weekly winner   WORKS
CREATE VIEW WEEKLY_WINNER
AS
	SELECT R.PARTICIPANT_ID, P.PERSON_NAME, R.EPISODE_ID, R.SEASON_ID, R.POINTS
	FROM FN71878.IS_RATED_IN R, FN71878.PEOPLE P
	WHERE R.PARTICIPANT_ID = P.PERSON_ID
	AND R.POINTS = 10@
	
SELECT * FROM WEEKLY_WINNER@

-- view for WOMEN WHO DO NOT HAVE NICKNAME -- WORKS

CREATE VIEW FEMALE_WITH_NICKNAME
AS
	SELECT PERSON_NAME
	FROM FN71878.PEOPLE
	WHERE GENDER='F'
	AND NICKNAME!='NULL'@

DROP VIEW FEMALE_WITH_NICKNAME@

SELECT * FROM FEMALE_WITHOUT_NICKNAME@