SET SCHEMA FN71878@
		
	
--- BEFORE TRIGGER    -> CREATED
CREATE TRIGGER FN71878.TRG_NICKNAME
BEFORE INSERT ON FN71878.PEOPLE
REFERENCING NEW AS n
FOR EACH ROW
MODE DB2SQL
WHEN (n.NICKNAME IS NULL)
	SET n.NICKNAME = n.PERSON_NAME@
	
INSERT INTO PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB) 
VALUES ('Kiril Kirov', null, 'M', 43, 'director')@

DROP TRIGGER TRG_NICKNAME@

-- TRIGGER WITH STORED PROCEDURE   -> CREATED
CREATE PROCEDURE FN71878.person_from_people(IN v_id INTEGER)
DYNAMIC RESULT SETS 1
BEGIN
	DECLARE c1 CURSOR WITH RETURN FOR SELECT * FROM FN71878.PEOPLE WHERE PERSON_ID = v_id;
OPEN c1;
CLOSE c1;
END@

DROP PROCEDURE person_from_people@

CALL FN71878.person_from_people('15')@


-- > CREATED
CREATE TRIGGER TRG_AGE
	AFTER INSERT ON FN71878.PEOPLE
	REFERENCING NEW AS n
	FOR EACH ROW
	BEGIN ATOMIC
		UPDATE FN71878.PEOPLE
		SET AGE = AGE + 2;
		CALL FN71878.person_from_people('15');
END@	


INSERT INTO FN71878.PEOPLE(PERSON_NAME, NICKNAME, GENDER, AGE, JOB)
VALUES ("Iva Ivanova", NULL, 'F', 51, "make-up artist")@




