SET SCHEMA FN71878@

-------CREATE TABLES   --CREATED
-- PEOPLE
CREATE TABLE PEOPLE(
PERSON_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
PERSON_NAME VARCHAR(64) NOT NULL, 
NICKNAME VARCHAR(32), 
GENDER CHAR(3),
AGE INT,
JOB VARCHAR(32),

CONSTRAINT PK_PEOPLE PRIMARY KEY(PERSON_ID),

CONSTRAINT GENDER_CHECK CHECK (GENDER='M' OR GENDER='F'),
CHECK (AGE > 18)
)@

-- JUDGES  -- CREATED
CREATE TABLE JUDGES(
JUDGE_ID INT NOT NULL REFERENCES PEOPLE (PERSON_ID),

PRIMARY KEY (JUDGE_ID)
--FOREIGN KEY (JUDGE_ID) REFERENCES PEOPLE (PERSON_ID) ON DELETE CASCADE ON UPDATE RESTRICT
)@

--HOSTS  -- CREATED 
CREATE TABLE HOSTS(
HOST_ID INT NOT NULL REFERENCES PEOPLE(PERSON_ID),

PRIMARY KEY(HOST_ID)
--FOREIGN KEY (HOST_ID) REFERENCES PEOPLE (PERSON_ID) ON DELETE CASCADE ON UPDATE RESTRICT
)@

--STAFF  - CREATED 
CREATE TABLE STAFF(
POSITION VARCHAR(32), 
STAFF_ID INT NOT NULL REFERENCES PEOPLE(PERSON_ID),

PRIMARY KEY (STAFF_ID)
--FOREIGN KEY (STAFF_ID) REFERENCES PEOPLE (PERSON_ID) ON DELETE CASCADE ON UPDATE RESTRICT
)@

--PARTICIPANTS   CREATED!!
CREATE TABLE PARTICIPANTS(
PARTICIPANT_ID INT NOT NULL REFERENCES PEOPLE(PERSON_ID),
SUMPOINTS INT NOT NULL,

PRIMARY KEY (PARTICIPANT_ID),
FOREIGN KEY (PARTICIPANT_ID) REFERENCES PEOPLE (PERSON_ID) ON DELETE CASCADE ON UPDATE RESTRICT,

CHECK (SUMPOINTS > 0)
)@


-- SEASON  -- CREATED
CREATE TABLE SEASON(
SEASON_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TV_CHANNEL VARCHAR(32) NOT NULL,
YEAR_OF_BROADCASTING INT NOT NULL, 
EPISODES INT NOT NULL, 
START_DATE DATE NOT NULL,
FINAL_DATE DATE NOT NULL, 
AWARD VARCHAR(32) NOT NULL, 
WINNER_ID INT NOT NULL, 

CONSTRAINT PK_SEASON PRIMARY KEY(SEASON_ID),
FOREIGN KEY (WINNER_ID) REFERENCES PARTICIPANTS (PARTICIPANT_ID),

CHECK (YEAR_OF_BROADCASTING >= 2013),
CHECK (EPISODES >= 12), 
CHECK (FINAL_DATE > START_DATE)
)@

ALTER TABLE FN71878.SEASON
ADD CONSTRAINT FK_WINNER_ID FOREIGN KEY (WINNER_ID) REFERENCES FN71878.PARTICIPANTS(PARTICIPANT_ID)@

-- EPISODE  -- CREATED
CREATE TABLE EPISODE(
EPISODE_ID INT NOT NULL,
SEASON_ID INT NOT NULL REFERENCES SEASON (SEASON_ID), 

CONSTRAINT PK_EPISODE_ID PRIMARY KEY(EPISODE_ID, SEASON_ID)
)@

-- GENERATED_IMPRESSION  CREATED
CREATE TABLE GENERATED_IMPRESSION(
SINGER_NAME VARCHAR(64) NOT NULL, 
SONG_NAME VARCHAR(64) NOT NULL, 

PARTICIPANT_ID INT NOT NULL, 
EPISODE_ID INT NOT NULL, 
SEASON_ID INT NOT NULL,

FOREIGN KEY (PARTICIPANT_ID) REFERENCES PARTICIPANTS (PARTICIPANT_ID),
FOREIGN KEY (EPISODE_ID, SEASON_ID) REFERENCES EPISODE (EPISODE_ID, SEASON_ID) 
)@

ALTER TABLE FN71878.GENERATED_IMPRESSION
ADD CONSTRAINT FK_PARTICIPANT_ID FOREIGN KEY (PARTICIPANT_ID) REFERENCES FN71878.PARTICIPANTS(PARTICIPANT_ID)@

-- IS_RATED_IN --CREATED
CREATE TABLE IS_RATED_IN (
PARTICIPANT_ID INT NOT NULL, 
EPISODE_ID INT NOT NULL, 
SEASON_ID INT NOT NULL,
POINTS INT NOT NULL,

FOREIGN KEY (EPISODE_ID, SEASON_ID) REFERENCES EPISODE (EPISODE_ID, SEASON_ID),

CHECK (POINTS >= 3 AND POINTS <= 11)
)@

ALTER TABLE IS_RATED_IN 
ADD CONSTRAINT FK_PARTICIPANT_ID FOREIGN KEY (PARTICIPANT_ID) REFERENCES FN71878.PARTICIPANTS (PARTICIPANT_ID)@

DROP TABLE IS_RATED_IN@

-- PARTICIPATE IN   -- CREATED
CREATE TABLE PARTICIPATE_IN(
PERSON_ID INT NOT NULL, 
SEASON_ID INT NOT NULL,

FOREIGN KEY (PERSON_ID) REFERENCES PEOPLE (PERSON_ID),
FOREIGN KEY (SEASON_ID) REFERENCES SEASON (SEASON_ID)
)@

DROP TABLE PARTCIPATE_IN@