SET SCHEMA FN71878@


-- cursor and in/ out    ->created ->WORKS
CREATE PROCEDURE PROJECT_PROC1(IN v_person_id INTEGER, OUT v_name VARCHAR(64))
RESULT SETS 1
BEGIN
	
	FOR v1 AS c1 CURSOR FOR SELECT PERSON_ID, PERSON_NAME FROM PEOPLE
	DO
	IF(PERSON_ID=v_person_id)
	THEN SET v_name = PERSON_NAME;
	
	END IF;
	END FOR;

END@

CALL FN71878.PROJECT_PROC1('5', ?)@    
DROP PROCEDURE FN71878.PROJECT_PROC1@

-- with execution              ->cretaed
CREATE PROCEDURE PROJECT_PROC2(OUT v_nickname VARCHAR(32)) -- OUT v_nickname VARCHAR(32)
LANGUAGE SQL
SPECIFIC MYPROJECT_PROCEDURE2
BEGIN
	DECLARE flag INTEGER DEFAULT 0;
	DECLARE v_id INTEGER;
	DECLARE v_nickname VARCHAR(32);
	
	DECLARE c1 CURSOR FOR SELECT PERSON_ID, NICKNAME FROM FN71878.PEOPLE; 
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET flag = 1;
	
	OPEN c1;
		 WHILE(flag = 1) DO
		 	FETCH c1 INTO v_id, v_nickname;
		 	IF(v_id='12')
		 	THEN SET v_nickname= v_nickname || '1';
		 	
		 	
		 	END IF;
		 END WHILE;
	CLOSE c1;
END@

DROP PROCEDURE PROJECT_PROC2@

CALL FN71878.PROJECT_PROC2(?)@ 

--with cursor and while    -->CREATED   ->NOT WORKING
CREATE PROCEDURE PROJECT_PROC3(OUT v_age INTEGER)
LANGUAGE SQL
BEGIN
	DECLARE v_person_id INTEGER;
	DECLARE v_person_name VARCHAR(64);
	DECLARE v_age INTEGER;
	DECLARE c1 CURSOR FOR SELECT PERSON_ID, PERSON_NAME, AGE FROM PEOPLE;
	
	OPEN c1;
	FETCH FROM c1 INTO v_person_id, v_person_name, v_age;
	
	WHILE(v_person_id < 90) DO
	
	IF(v_person_id='60')
	THEN
	SET v_age = v_age + 1;
	END IF;
	
	END WHILE;
	CLOSE c1;
END@

CALL FN71878.PROJECT_PROC3(?)@
DROP PROCEDURE FN71878.PROJECT_PROC3@