SET SCHEMA FN71878@


-------------------------insert generated impressions for season 3 ----------------------------

-- SEASON 3 EPISODE 1---- SEASON 3 -> SEASON_ID = 25    ALL DONE
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Preah','Malkite neshta',22,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,1,25,8)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Indila','Darniere Dance',23,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,1,25,4)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Pitbull','I know you want me',20,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,1,25,5)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Shirley Bassey','Big spender',21,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,1,25,7)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('PSY','Gentleman',24,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,1,25,10)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Yordanka Hristova','Tezhak harakter',18,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,1,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Freddie Mercury and Queen','Somebody to love',19,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,1,25,6)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Lili Ivanova','Vetre, kleh te',17,1,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,1,25,9)@

--------- SEASON 03 EPISODE 2   ALL DONE ------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Eros Ramazzotti','Fuoco nel fuoco',22,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,2,25,9)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Etien Levi and Trick','Shesto chuvstvo',23,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,2,25,7)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Mihaela Fileva','Prilivi i otlivi',20,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,2,25,6)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Nicole Scherzinger and Pussycat Dolls','Sway',21,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,2,25,5)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Tina Turner','Proud Mary',24,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,2,25,8)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Vanessa Paradis','Joe le taxi',18,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,2,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Rihanna','Stay/Umbrella',19,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,2,25,4)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Slavi Trifonov and Ku-Ku bend','Ad i rai',17,2,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,2,25,10)@

---------------------SEASON 3 EPISODE 3   ALL DONE------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Deqn Nedelchev','V gorata',22,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,3,25,10)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Fergie','A little party never killed nobody',23,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,3,25,3)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Cheb Khaled','Aicha',20,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,3,25,8)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Katy Perry','I kissed a girl',21,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,3,25,4)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Tom Jones','If I only knew',24,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,3,25,5)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Kaoma','Lambada',18,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,3,25,6)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Steven Tyler and Aerosmith','Crazy',19,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,3,25,7)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Georgi Hristov','Cherno i bqlo',17,3,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,3,25,9)@


---------------------SEASON 3 EPISODE 4      ALL DONE------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Enrique Iglesias','Hero',22,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,4,25,10)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Madonna','La isla bonita',23,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,4,25,3)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Emil Dimitrov','Nashiqt signal',20,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,4,25,9)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Mihail Boqrskii','Pesnq mushketerov',21,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,4,25,5)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('100 kila and Magi Djanavarova','Moeto radio',24,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,4,25,6)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Kylie Minogue','The loco-motion',18,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,4,25,4)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Lili Ivanova','Osadeni dushi',19,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,4,25,8)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Sabrina','Boys (Summertime love)',17,4,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,4,25,7)@


---------------------SEASON 3 EPISODE 5    ALL DONE-----------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Krisko','Bilo kvot bilo',22,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,5,25,10)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Maria Callas','Habanera Carmen',23,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,5,25,5)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Justin Timberlake','Sexyback',20,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,5,25,8)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Doni and Momchil','Shapka na cvetni petna',21,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,5,25,4)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Sher','Dov''e L''amore',24,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,5,25,7)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Karizma','Minavash prez men',18,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,5,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Bob Marley','Could you be loved',19,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,5,25,6)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Michael Jackson','Billie Jean',17,5,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,5,25,9)@




---------------------SEASON 3 EPISODE 6   ALL DONE---------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Meghan Trainor','All about that bass',22,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,6,25,10)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Elvis Presley','Can''t help falling in love',23,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,6,25,4)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Adele','Rolling in the deep',20,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,6,25,5)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Bruno Mars','Uptown funk',21,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,6,25,7)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('AC/DC','You shook me all night long',24,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,6,25,9)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Michael Jackson','You are not alone',18,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,6,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Milena Slavova','Ha-ha',19,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,6,25,8)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Beyonce','Naughty girl',17,6,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,6,25,6)@



---------------------SEASON 3 EPISODE 7   ALL DONE------------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Veselin Marinov','Rozhden den',22,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,7,25,7)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Meryl Streep','Mamma Mia',23,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,7,25,4)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Slang','Moi svqt',20,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,7,25,9)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Madonna','Material girl',21,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,7,25,5)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('James Brown','I got you (I feel good)',24,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,7,25,10)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Dolly Parton','I will always love you',18,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,7,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Taylor Swift','Shake it off',19,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,7,25,8)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Yanka Rupkina','Kalimanku Denku',17,7,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,7,25,6)@



---------------------SEASON 3 EPISODE 8   ALL DONE--------------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Pitbull','Fireball',22,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,8,25,7)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Sade','Smooth operator',23,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,8,25,3)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Nicki Minaj','Anaconda',20,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,8,25,10)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Marlene Dietrich','Lili Marleen',21,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,8,25,9)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Pink','Try',24,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,8,25,8)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Adriano Celentano','Il tempo se ne va',18,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,8,25,4)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Guns N'' Roses','Paradise city',19,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,8,25,6)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Zhana Bergendorf','Samurai',17,8,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,8,25,5)@





---------------------SEASON 3 EPISODE 9      ALL DONE-------------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Kamelia Todorova','Ne me gledai taka momche',22,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,9,25,8)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Michael Jackson','Remember the time',23,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,9,25,3)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Irina Florin','Cviat lilav',20,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,9,25,5)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Cher','Strong enough',21,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,9,25,6)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Neti','Lunata spi',24,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,9,25,4)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Maia Neshkova','Chestit Rojden Den',18,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,9,25,7)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Beyonce','Listen',19,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,9,25,9)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Stevie Wonder','I just called to say I love you',17,9,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,9,25,10)@



---------------------SEASON 3 EPISODE 10     ALL DONE----------------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Prince','The most beautiful girl in the world',22,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,10,25,7)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Lea Ivanova','Shusho-musho',23,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,10,25,6)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Ray Charles','Hit the road Jack',20,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,10,25,8)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Zaz','Je veux',21,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,10,25,5)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Whitesnake','Here I go again',24,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,10,25,9)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Chubby Checker','Limbo rock',18,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,10,25,3)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Philip Kirkorov','Mne mama toho govorila',19,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,10,25,4)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Ahat','Cherna ovca',17,10,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,10,25,10)@



---------------------SEASON 3 EPISODE 11     ALL DONE-----------------------------------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Tarkan','Simarik/Kiss kiss',22,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (22,11,25,10)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Demis Roussos','Goodbye my love',23,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (23,11,25,3)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Eminem','The real Slim Shady',20,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (20,11,25,7)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Louis Armstrong','Hello Dolly',21,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (21,11,25,4)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Silvia Kacarova and Vasil Naidenov','Ogan ot lubov',24,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (24,11,25,8)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Slavka Kalcheva','Biala rosa',18,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (18,11,25,5)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Jessie J','Mama knows best',19,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (19,11,25,6)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Diana Express','Dusha',17,11,25)@
INSERT INTO IS_RATED_IN(PARTICIPANT_ID, EPISODE_ID, SEASON_ID, POINTS)
VALUES (17,11,25,9)@




---------------------SEASON 3 EPISODE 12     ALL DONE---------------------------------------------------------
-- nencho
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Koceto Kalki','Vekat na lubovta',22,12,25)@
--nona
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Tonika','Zdravei, kak si, priqtelu',23,12,25)@
--krisko
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Nirvana','Smells like teen spirit',20,12,25)@
--maca
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Elton John and RuPaul','Don''t go breakin'' my heart',21,12,25)@
--filip
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Todor Kolev','Kak shte gi stignem amerikancite',24,12,25)@
--djudji
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Tonika','Zdravei, kak si, priqtelu',18,12,25)@
--jana
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('Elton John and RuPaul','Don''t go breakin'' my heart',19,12,25)@
--azis
INSERT INTO GENERATED_IMPRESSION(SINGER_NAME, SONG_NAME, PARTICIPANT_ID, EPISODE_ID, SEASON_ID)
VALUES ('CECA','Kukavica',17,12,25)@

















